### ISSUE TITLE
What is the Training time for UCF101 and MineRL dataset?

### ISSUE THREAD

**Issue by amandpkr** [shim0114/SSM-Meets-Video-Diffusion-Models#2]
Hi Authors,

Hope you are doing well.

Can you please let me know what is training time for your model for both the dataset

**Comment by shim0114** [comment]
Thank you for your asking!
Now we have updated Readme and shown device details.

| Dataset          | UCF101         | UCF101         | MineRL         | MineRL         |
|------------------|----------------|----------------|----------------|----------------|
| **# of Frames**  | 16             | 16             | 64             | 150            |
| **Resolution**   | $32 \times 32$ | $64 \times 64$ | $32 \times 32$ | $32 \times 32$ |
| **GPUs** | V100 $\times 4$ | A100 $\times 8$ | V100 $\times 4$ | V100 $\times 4$ |
| **Training Time** | 72 hours | 120 hours | 72 hours | 72 hours |

**Comment by amandpkr** [comment]
Thank you very much authors for prompt response.

Can you also please provide the steps for setting up dataset?

Thanking you in advance

**Comment by shim0114** [comment]
That's a very fair point, thank you!

| Dataset          | UCF101         | UCF101         | MineRL         | MineRL         |
|------------------|----------------|----------------|----------------|----------------|
| **# of Frames**  | 16             | 16             | 64             | 150            |
| **Resolution**   | $32 \times 32$ | $64 \times 64$ | $32 \times 32$ | $32 \times 32$ |
| **Training steps** | 92k | 106k | 174k | 129k |
| **GPUs** | V100 $\times 4$ | A100 $\times 8$ | V100 $\times 4$ | V100 $\times 4$ |
| **Training Time** | 72 hours | 120 hours | 72 hours | 72 hours |

**Comment by amandpkr** [comment]
Thank you for your information.

I just wanted to ask about the instruction to step up for both datasets. like what are the preprocessing or the desired folder layout structure to run the code. Like url to download **MineRL Navigate dataset**

**Comment by shim0114** [comment]
## Downloading Datasets
### UCF101
1. Please follow the commands shown in `./dl_ucf101.ipynb` to download datasets.
2.  Specify `ucf101-all` as `dataset` and `.` as `--folder`.

### MineRL Navigate
1. Execute a following python code.
```
python dl_mine_rl.py
```
2. Specify `minerl` as `--dataset` and `minerl_navigate-torch` as `--folder`.
