### ISSUE TITLE
GLU or not ? 

### ISSUE THREAD

**Issue by ABH2024** [shim0114/SSM-Meets-Video-Diffusion-Models#4]
Hello, 
Thank you for this implementation of your paper .
I had a question, if i understood well version 16 is the code described in the paper but i am not able to understand why in Unet3D in here "elif version in range(16, 19) or version == 21:
            self.s4d = S4D(dim, hidden_dim, transposed=False, output_glu=False)
            if bidirectional:
                self.s4d_rev = S4D(dim, hidden_dim, transposed=False, output_glu=False)" , the GLU output is False ? 
Because in the model described in the paper GLU layer is used . 
I am a bit confused about this part of the code . 

Thank you in advance,
A.B.H

**Comment by shim0114** [comment]
Thank you for your question.
In fact, version 16 is not described in our paper (GLU ablations are implemented in our code but experiments are not conducted).
The main architecture we explained in our paper is version 8.
In version 8, Bidirectional SSMs with GLUs are followed by a MLP. 
This corresponds to the architectures shown in Figure 1 (b) (c).

**Comment by ABH2024** [comment]
Ahh ok , thank you for your answer . 
Just another question then , why here : python train_video-diffusion.py 
--timesteps 256 --loss_type 'l2' --train_lr 0.0003 --train_num_steps 700000 --train_batch_size 16 --gradient_accumulate_every 2 --ema_decay 0.995 # Learning Settings
--base_channel_size 64 --timeemb_linears 2 # Architecture Settings
--temporal_layer 'bi-s4d' --s4d_version 16 # Temporal Layer Settings
--image_size 32 --dataset 'ucf101-all' # Dataset Settings
--folder 'path/to/datasets' 
--results_folder 'path/to/save' 
--device_ids 0 1 2 3 # GPU Settings

s4d_version is 16 ?

This is the reason why i focused on the version 16.

Bests,
A.B.H

**Comment by shim0114** [comment]
Thank you for your observation. 
I agree this could be confusing, so I have updated the README.
